services:
  api-gateway:
    build: ./api-gateway
    ports:
      - 3000:3000
    env_file: ./api-gateway/.env
    depends_on:
      - rabbitmq
      - user-db
      - ride-db
      - captian-db
      
    environment:
      RABBITMQ_URL: amqp://@rabbitmq:5672

  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    depends_on:
      - user-db
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:postgres@user-db:5432/user_service

  ride-service:
    build: ./ride-service
    env_file: ./ride-service/.env
    depends_on:
      - ride-db
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:postgres@ride-db:5432/ride_service

  captain-service:
    build: ./captian-service
    env_file: ./captian-service/.env
    depends_on:
      - captian-db
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:postgres@captian-db:5432/captian_service

  # Add RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # postgres  database  for each service


# user-db
  user-db:
    image: postgres
    restart: always
    volumes:
      - ./data/user-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=user_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


# ride-db
  ride-db:
    image: postgres
    restart: always
    volumes:
      - ./data/ride-db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=ride_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

# captain-db
  captian-db:
    image: postgres
    restart: always
    volumes:
      - ./data/captian-db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=captian_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

